<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sam Schurkamp">

<title>Exploring New Ways to Determine the Value of Combining ARUs and PCs</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="NewARUvsCombinedAnalyses_files/libs/clipboard/clipboard.min.js"></script>
<script src="NewARUvsCombinedAnalyses_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="NewARUvsCombinedAnalyses_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="NewARUvsCombinedAnalyses_files/libs/quarto-html/popper.min.js"></script>
<script src="NewARUvsCombinedAnalyses_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="NewARUvsCombinedAnalyses_files/libs/quarto-html/anchor.min.js"></script>
<link href="NewARUvsCombinedAnalyses_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="NewARUvsCombinedAnalyses_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="NewARUvsCombinedAnalyses_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="NewARUvsCombinedAnalyses_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="NewARUvsCombinedAnalyses_files/libs/bootstrap/bootstrap-917079515d91bccb85b543faf8aa8bb6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exploring New Ways to Determine the Value of Combining ARUs and PCs</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sam Schurkamp </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="overview-of-the-problem" class="level2">
<h2 class="anchored" data-anchor-id="overview-of-the-problem">Overview of the Problem</h2>
<p>In our original manuscript submission, we used binomial tests to see if there were meaningful differences between the species richness of ARUs, point counts (PCs), and each method relative to the combined total of both methods. The data is structured like this:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    Point Route Year ARU PC ARU + PC
1 BIGM-02  BIGM 2022   8  4        8
2 BIGM-02  BIGM 2024   5  5        6
3 BIGM-03  BIGM 2022   6  5        7
4 BIGM-03  BIGM 2024   6  4        6
5 BIGM-11  BIGM 2022   4  4        5
6 BIGM-11  BIGM 2024   9  3        9</code></pre>
</div>
</div>
<p>Note that the <strong>ARU + PC</strong> column is not necessarily the value in <strong>ARU</strong> plus the value in <strong>PC</strong>. That is because <strong>ARU + PC</strong> represents <em>all unique species found at that site across all methods</em>, and ARUs and PCs often found the same species in the same location. In other words, the <strong>ARU + PC</strong> value in the first row of the dataset is 8 because all four species found by PC were also found by ARUs, and ARUs found four additional species. In the case where all three values are equal, both methods had an identical species list; when both <strong>ARU</strong> and <strong>PC</strong> are equal but <strong>ARU + PC</strong> is larger than both, it is because each method found one unique species.</p>
<p>Binomial tests were appropriate for the ARU vs.&nbsp;PC test because this statistical method works well when comparing two methods of Poisson-distributed data, but they were not appropriate for the combination. Binomial tests ignore all ties, and since the combined dataset by definition could not be smaller than either individual method, the tests were highly likely to find significant differences regardless of whether or not they actually differed.</p>
<p>In other words, the figure reproduced below from our initial submission includes two graphs that are ultimately misleading: the middle-right and bottom-right. We should also remove the bottom-left graph for reasons that will become apparent by the end of this document (as a spoiler, the best method I found doesn’t rely as heavily on that data directly and it is not valuable to show its theoretical vs.&nbsp;observed distributions).</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="NewARUvsCombinedAnalyses_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>The figure in our original manuscript. I propose removing both bottom and the middle-right graphs.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="what-we-want-to-do" class="level2">
<h2 class="anchored" data-anchor-id="what-we-want-to-do">What We Want to Do</h2>
<p>The overarching goal of the original analysis was to determine whether using <em>both</em> ARUs and PCs was more valuable than using one method alone. We already know that ARUs found more species than PCs at almost every site, so it is not that interesting to ask the following question:</p>
<p><em>Are more species detected when deploying ARUs and PCs than when only PCs are performed?</em></p>
<p>We already know the answer. Not only is the answer yes, but ARUs alone outperformed PCs alone. However, we can easily recognize that ARUs often missed species that PCs found. A more direct question, then, is:</p>
<p><em>Do PCs meaningfully contribute to a dataset when ARUs are deployed?</em></p>
<p>An alternative way of stating this question: <strong>how much value would be added by deploying PCs when ARUs are also going to be capturing data?</strong></p>
</section>
<section id="new-approaches" class="level2">
<h2 class="anchored" data-anchor-id="new-approaches">New approaches</h2>
<p>After Drew and I talked through this problem and the potential ways we could run an appropriate analysis, I used generative AI through UMich’s portal at Drew’s suggestion to see what sorts of analysis it recommended. The following suggestions came from GPT-5.6 Sol, but I only quote it directly when italicized. All non-italic text is my own writing, and I also read the theory and applications of each statistical method in verified human-written sources before proceeding.</p>
<p>I also obtained code from this AI search, but independently checked each component and rewrote all lines of code in the syntax, order, and commenting that made sense to me. The following options were what the AI proposed:</p>
<section id="paired-nonparametric-analysis" class="level3">
<h3 class="anchored" data-anchor-id="paired-nonparametric-analysis">Paired nonparametric analysis</h3>
<p>This approach works when sites are independent and there is one matched observation per site, but because it is nonparametic we lose some statistical power.I wrote this option down for posterity’s sake, but I think our data are clean enough that we don’t need to resort to non-parametric testing.</p>
</section>
<section id="count-regression-using-a-negative-binomial-generalized-linear-mixed-model" class="level3">
<h3 class="anchored" data-anchor-id="count-regression-using-a-negative-binomial-generalized-linear-mixed-model">Count regression using a negative-binomial generalized linear mixed model</h3>
<p>This method estimates the number of species added by using two methods instead of one. In our case, that would mean the number of species added if we run PCs in addition to using ARUs. Per ChatGPT:</p>
<p><em>Testing whether the model’s mean is greater than zero is awkward because zero is the boundary of the count distribution. It is often better to report</em></p>
<ul>
<li><em>estimated mean number of added species</em></li>
<li><em>confidence interval</em></li>
<li><em>proportion of sampling units for which at least one species was added</em></li>
<li><em>distribution of the gain across sites</em></li>
</ul>
<p>ChatGPT also mentioned that this model might struggle if many values are close to zero, and many of our values are. As a result, I went forward with the next option, which is similar but handles low values better.</p>
</section>
<section id="hurdle-negative-binomial-model" class="level3">
<h3 class="anchored" data-anchor-id="hurdle-negative-binomial-model">Hurdle negative-binomial model</h3>
<p><strong>This appears to be the strongest option and it is the one I proceeded with.</strong> It is used specifically for count data that has a lot of zeroes, and I found several citations that used this approach for bird count data. A hurdle negative-binomial model asks two separate questions:</p>
<ul>
<li>What is the probability that the second method adds at least one species?</li>
<li>Among surveys where it adds species, how many does it add?</li>
</ul>
<p><strong>Based on what we know, I believe these two questions are the most relevant to what we want to show in our paper given the statistical tools and study design at our disposal.</strong> Again, this framework is a slight shift from our original paper, where we asked if the combination of both datasets was higher significantly higher than either individual dataset. Here, we are specifically testing whether conducting PCs <em>in addition to ARUs</em>, not the other way around, is more valuable than only using ARUs. As stated before, the reasoning here is that we already know the answer in the other direction, but now we want a clear way to determine whether ARUs wholly replace PCs (from a data perspective).</p>
</section>
</section>
<section id="running-the-hurdle-negative-binomial-model" class="level2">
<h2 class="anchored" data-anchor-id="running-the-hurdle-negative-binomial-model">Running the Hurdle negative-binomial model</h2>
<p>After we format our data, we do actually have a lot of zeroes: the relevant data are the <strong>total number of species found by ARUs</strong> and <strong>total number of species missed by ARUS.</strong> That second number is synonymous with “total number of species found <em>only</em> by PC at a given site, and in our dataset, it’s 0 in 39 of 60 cases. Here’s the same table as above but with the additional column for the number of species ARUs missed at each site:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    Point Route Year ARU PC ARU + PC OnlyFoundByPC
1 BIGM-02  BIGM 2022   8  4        8             0
2 BIGM-02  BIGM 2024   5  5        6             1
3 BIGM-03  BIGM 2022   6  5        7             1
4 BIGM-03  BIGM 2024   6  4        6             0
5 BIGM-11  BIGM 2022   4  4        5             1
6 BIGM-11  BIGM 2024   9  3        9             0</code></pre>
</div>
</div>
<p>UMich’s AI did not direct me to check assumptions before this test, so the rest of this information comes from my digging around. A hurdle negative-binomial model makes the following assumptions about the data:</p>
<ol type="1">
<li>The response variable represents counts that have meaningful zeroes. A “0” in any given row means that PCs did not find any species that ARUs did not.</li>
<li>All sampling units are comparable and all observations are conditionally independent. Different rows should not reflect repeated sampling at a given site.</li>
<li>The dataset includes “enough” zero and positive observations. I couldn’t find any hard numbers for what enough means, but I know from testing out code in the following sections that the packages tell you when your data is insufficient. It also gives a warning for nonconvergence (see below).</li>
<li>The model doesn’t assign an observed probability to zero, since only positive observations get included in the first part of the hurdle. There’s a specific line of code that ensures this step.</li>
<li>Random effects are accounted for</li>
<li>Other predictors are not collinear</li>
<li>No observations have an outsized effect on the model.</li>
<li>The model converges on a set of model parameters.</li>
</ol>
<p>Many of these assumptions are solved at the experimental design stage, and the rest can be checked with the model outputs. I could not find any statistical assumption tests I needed to run before proceeding.</p>
</section>
<section id="question-1-does-pc-detect-additional-species-that-aru-did-not" class="level2">
<h2 class="anchored" data-anchor-id="question-1-does-pc-detect-additional-species-that-aru-did-not">Question 1: Does PC detect additional species that ARU did not?</h2>
<p>In order to do the first step, the model needs binary data. All data from <strong>OnlyFoundByPC</strong> gets converted to either a 1 (if any additional species were found) or a 0 (no additional species were found). The model then works with this binary data.</p>
<p>All code for this step is as follows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># convert to binary</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>all_data_long <span class="ot">&lt;-</span> all_data_long <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">UniquePC_binary =</span> <span class="fu">as.integer</span>(OnlyFoundByPC <span class="sc">&gt;</span> <span class="dv">0</span>))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># make sure "route" is a factor</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>all_data_long<span class="sc">$</span>Route <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(all_data_long<span class="sc">$</span>Route)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># build the model</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>Hurdle1 <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(UniquePC_binary <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>Route),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">family =</span> binomial,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> all_data_long)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co"># </span><span class="al">NOTE</span><span class="co">: "Route" is the same to us as "Wetland". This code accounts for each location as a random effect.</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co"># view the output of the model</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Hurdle1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: binomial  ( logit )
Formula:          UniquePC_binary ~ 1 + (1 | Route)
Data: all_data_long

      AIC       BIC    logLik -2*log(L)  df.resid 
     81.7      85.9     -38.8      77.7        58 

Random effects:

Conditional model:
 Groups Name        Variance  Std.Dev. 
 Route  (Intercept) 3.775e-09 6.144e-05
Number of obs: 60, groups:  Route, 16

Conditional model:
            Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)  -0.6190     0.2707  -2.287   0.0222 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>**With a p-value of 0.0222, we can conclude that adding PC observations DOES detect additional species than if we only used ARU data.**</p>
</section>
<section id="question-2-among-surveys-where-pcs-adds-species-how-many-do-they-add" class="level2">
<h2 class="anchored" data-anchor-id="question-2-among-surveys-where-pcs-adds-species-how-many-do-they-add">Question 2: Among surveys where PCs adds species, how many do they add?</h2>
<p>Now that we know that PCs add additional species, we need to know how many they add. We can do that with the following code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># build the model.</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Very similar to Hurdle1, but no longer with binary data.</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># After some trial and error, these models work better when you subset the data ahead of time:</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>positive_data <span class="ot">&lt;-</span> <span class="fu">subset</span>(all_data_long, OnlyFoundByPC <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># The following code is the most robust model but it has a handful of problems:</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. There are not enough observations per route for it to be a useful random effect.</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. There is only one positive observation for many routes.</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. There is little variation in the positive_data dataset; all values are either 1 or 2.</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co">#  Hurdle2 &lt;- glmmTMB(</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a> <span class="co">#   OnlyFoundByPC ~ 1 + (1|Route),</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="co">#  family = truncated_nbinom2,</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>   <span class="co"># data = positive_data</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a> <span class="co"># )</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a> <span class="co"># so the next step is to try a simpler model. A truncated Poisson has no separate negative-binomial dispersion parameter, so it is easier to estimate. I can do so without dropping the Route random effect, but will do so if I continue to get warning messages.</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>Hurdle2_pois <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>  OnlyFoundByPC <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Route),</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> truncated_poisson,</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> positive_data</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>After building the model, the following code should be run:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>Hurdle2_pois<span class="sc">$</span>sdr<span class="sc">$</span>pdHess</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>Because this code returns TRUE, we know (per ChatGPT): <em>the Hessian matrix is positive definite, indicating that glmmTMB found a locally stable optimum and could calculate standard errors. Together with the absence of convergence warnings, this supports using the model estimates. It is a numerical convergence check, not a goodness-of-fit test.</em></p>
<p><em>It does not establish that:</em> <em>the truncated-Poisson distribution fits the data well;</em> <em>all model assumptions are met;</em> <em>PC provides an ecologically meaningful benefit.</em></p>
<p>As I understand it, as long as our code returns TRUE and we’ve been careful to choose the correct models, we have enough statistical power to proceed. A summary of the model renders:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Hurdle2_pois)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: truncated_poisson  ( log )
Formula:          OnlyFoundByPC ~ 1 + (1 | Route)
Data: positive_data

      AIC       BIC    logLik -2*log(L)  df.resid 
     21.8      23.9      -8.9      17.8        19 

Random effects:

Conditional model:
 Groups Name        Variance  Std.Dev. 
 Route  (Intercept) 1.498e-09 3.871e-05
Number of obs: 21, groups:  Route, 9

Conditional model:
            Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)  -1.2972     0.5652  -2.295   0.0217 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The relevant piece of information in this summary output is the Estimate column, which gives us the log-scale estimate of the amount of species added by PC when ARUs don’t capture them all. We can get the raw number by converting out of log-scale:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>beta0 <span class="ot">&lt;-</span> <span class="fu">fixef</span>(Hurdle2_pois)<span class="sc">$</span>cond[<span class="st">"(Intercept)"</span>]</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>lambda <span class="ot">&lt;-</span> <span class="fu">exp</span>(beta0)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>mean_when_positive <span class="ot">&lt;-</span> lambda <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">exp</span>(<span class="sc">-</span>lambda))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>lambda</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
  0.2732825 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>mean_when_positive</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   1.142857 </code></pre>
</div>
</div>
<p>There we have it: when ARUs miss a species at a site, PCs provide an additional 1.14 species to the overall dataset.</p>
</section>
<section id="putting-it-all-together" class="level2">
<h2 class="anchored" data-anchor-id="putting-it-all-together">Putting it all together</h2>
<p>By running a hurdle negative-binomial model, we learned that:</p>
<ol type="1">
<li>PCs do contribute additional species to the data provided by ARUs.</li>
<li>When they contribute data, they contribute roughly 1.14 species that ARUs missed.</li>
</ol>
<p>We can use this information to get an overall probability that a PC would add to an ARU dataset by multiplying the percent of rows in which PCs contributed novel data by the amount of species they contribute in those cases. That gives us:</p>
<p><span class="math display">\[
\frac{21 \text{ rows with PC-only species}}{60 \text{ total rows}} \times 1.14 = 0.399 \text{ expected added species per site overall}
\]</span></p>
</section>
<section id="appendix-writing-these-methods-and-results-out-to-be-added-to-the-manuscript" class="level2">
<h2 class="anchored" data-anchor-id="appendix-writing-these-methods-and-results-out-to-be-added-to-the-manuscript">APPENDIX: writing these methods and results out to be added to the manuscript</h2>
<section id="methods" class="level3">
<h3 class="anchored" data-anchor-id="methods">Methods</h3>
<p>After comparing ARU and PC species richness, we used a two-stage hurdle modeling approach to determine if using both ARUs and PCs leads to higher species richness than a scenario where only the more successful method were deployed. All assumptions for both models were validated before analysis.The first hurdle was a negative-binomial model that tested whether or not the second model significantly contributes observations, and the second hurdle was a zero-truncated Poisson mixed model to determine the relative contribution of the second method when it detected additional species. We included site as a random effect in both models. We then multiplied the relative contribution by the percent of sites at which an additional species was detected to obtain a value for the expected contribution of the second method across all sites.</p>
</section>
<section id="results" class="level3">
<h3 class="anchored" data-anchor-id="results">Results</h3>
<p>PCs detected at least one species not detected by ARUs at 35% of site-years. Hurdle negative-binomial models revealed this value is significant (p = 0.022) and that an estimated 1.14 species are detected when PCs detect a novel species. Averaged across all observations, utilizing both ARUs and PCs generates an expected contribution of 0.4 species per site relative to utilizing only ARUs.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>